import React from "react";
import "./About.css";
import homeImage from "../../assets/images/home/homeimage.png";
import { Divider } from "@chakra-ui/react";

export default function About() {
  return (
    <div className="home-container container">
      <div className="inner-container">
        <div className="text-section text-xl">
          <h1 className="text-4xl">
            <strong>Welcome to Westside Belle Cakery</strong>
          </h1>
          <p>
            Established last Tuesday, Westside Belle Cakery is steeped in a rich
            history that spans an entire week. As the world’s premier purveyor
            of AI-generated confections, we've been at the forefront of the
            baking industry since... well, last week.
          </p>
          <p>
            At Westside Belle, we blend the timeless art of pastry making with
            cutting-edge AI technology. Each of our cakes is crafted from images
            generated by the latest AI, ensuring that every swirl of icing and
            sprinkle of sugar is as unique as it is delicious.
          </p>

          <h3>
            <strong>Explore Our Time-Honored Selections and try...</strong>
          </h3>
          <ul>
            <li>
              <strong>Quantum Chocolate Fudge:</strong> A cake so indulgent, it
              defies the laws of physics.
            </li>
            <li>
              <strong>Vanilla Vortex:</strong> Swirled with the essence of
              vanilla beans that the AI dreamt existed.
            </li>
            <li>
              <strong>Raspberry Pi:</strong> Mathematically proven to be
              scrumptious.
            </li>
          </ul>
          <p>
            Join us at Westside Belle, where every cake is a masterpiece, every
            bite is a byte of bliss, and history is measured in software
            updates. Don’t miss out on the novelty of celebrating centuries of
            tradition—or at least the tradition that started last week.
          </p>
        </div>
        <div className="image-section">
          <img src={homeImage} alt="home image" />
        </div>
      </div>
    </div>
  );
}
